language: go
sudo: false
go:
  - 1.9
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
install:
  - go get github.com/hoisie/web
  - go get github.com/mgutz/str
  - go get github.com/PuerkitoBio/goquery